language: ruby
cache: bundler
rvm:
- 2.5
env:
- GEM_BOLT=true

before_install:
- git clone https://github.com/puppetlabs/puppetlabs-ruby_task_helper ../ruby_task_helper
- git clone https://github.com/puppetlabs/puppetlabs-ruby_plugin_helper ../ruby_plugin_helper
- curl -fSL "https://releases.hashicorp.com/terraform/0.12.13/terraform_0.12.13_linux_amd64.zip" -o terraform.zip
- sudo unzip terraform.zip -d /opt/terraform
- sudo ln -s /opt/terraform/terraform /usr/bin/terraform
- rm -f terraform.zip

script:
- bundle exec rubocop
- bundle exec rake spec


notifications:
  email: false
  